name: mattermost-digital-ocean

on: workflow_dispatch

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: install packages
    - run: npm ci
    - name: build app
    - run: npm run build

    - name: copy built file to digital ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "dist/*"
        target: "thuong/mattermost-webapp"
        rm: true
